#!/bin/sh

echo -e "
	 R G B | C
	-----------
	 5 5 5 | \\033[1;38;5;16;48;5;231m| White  |\\033[0m
	 5 0 0 | \\033[1;38;5;16;48;5;196m| Red    |\\033[0m
	 5 3 0 | \\033[1;38;5;16;48;5;214m| 0range |\\033[0m
	 5 5 0 | \\033[1;38;5;16;48;5;226m| Yellow |\\033[0m
	 0 5 0 | \\033[1;38;5;16;48;5;46m| Green  |\\033[0m
	 0 5 5 | \\033[1;38;5;16;48;5;21m| Blue   |\\033[0m
	 5 0 5 | \\033[1;38;5;16;48;5;201m| Pink   |\\033[0m
	 5 3 5 | \\033[1;38;5;16;48;5;129m| Purple |\\033[0m
	 0 3 5 | \\033[1;38;5;16;48;5;39m| Sky    |\\033[0m
	 0 5 5 | \\033[1;38;5;16;48;5;51m| Cyan   |\\033[0m
	 0 0 0 | \\033[1;38;5;231;48;5;16m| Black  |\\033[0m
"
echo -e "
	Enter ForeGround Color-Code :
"
read -p "	R : " fgr
read -p "	G : " fgg
read -p "	B : " fgb

echo -e "
        Enter BackGround Color-Code :
"
read -p "	R : " bgr
read -p "	G : " bgg
read -p "	B : " bgb

function RGBcolor {
    echo -e "16 + $1 * 36 + $2 * 6 + $3" | bc
}

fg=$(RGBcolor $fgr $fgg $fgb)
bg=$(RGBcolor $bgr $bgg $bgb)

$PREFIX/bin/termux-clipboard-set "\\\\\\\\033[1;38;5;$fg;48;5;${bg}m"

echo -e "\n\\033[1;38;5;$fg;48;5;${bg}m This Color Code Copied on ClipBoard \\033[0m"
