#!/bin/bash

function RGBcolor {
    echo -e "16 + $1 * 36 + $2 * 6 + $3" | bc
}

c=$(RGBcolor $3 $4 $5)

/data/data/com.termux/files/usr/bin/termux-clipboard-set "\\\\\\\\033[$1;${2}8;5;${c}m"

echo -e "\\033[${1};${2}8;5;${c}m$6\\033[0m"
